services:
  uptimepinger.server:
    image: ${DOCKER_REGISTRY-}uptimepingerserver
    container_name: uptimepinger-server
    build:
      context: ./UptimePinger.Server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - uptimepinger.db
      - uptimepinger.seq
    secrets:
      - pg_connection_string
    environment:
      ConnectionStrings__DefaultConnection: /run/secrets/pg_connection_string
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend-net

  uptimepinger.db:
    image: postgres:17
    container_name: uptimepinger-db
    restart: always
    secrets:
      - pg_user
      - pg_password
    environment:
      POSTGRES_USER: /run/secrets/pg_user
      POSTGRES_PASSWORD: /run/secrets/pg_password
      POSTGRES_DB: UptimePinger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net

  uptimepinger.seq:
    image: datalust/seq:latest
    container_name: uptimepinger-seq
    secrets:
      - seq_admin_password
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: /run/secrets/seq_admin_password
    ports:
      - "5341:80"      # Inbound ingestion
      - "5342:5342"    # UI
    networks:
      - backend-net

  uptimepinger.client:
    container_name: uptimepinger-client
    build:
      context: ./uptimepinger.client
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_HTTPS_PORT: 8080
    ports:
      - "4200:80"
      - "4659:4659"
    depends_on:
      - uptimepinger.server
    networks:
      - backend-net

volumes:
  pgdata:
  seqdata:

networks:
  backend-net:
  
secrets:
    pg_connection_string:
        file: ./secrets/pg_connection_string.txt
    pg_user:
        file: ./secrets/pg_user.txt
    pg_password:
        file: ./secrets/pg_password.txt
    seq_admin_password:
        file: ./secrets/seq_admin_password.txt